# Use an official Python runtime as a base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the Flask app runs on (5001 in this case)
EXPOSE 5001

# Run the Flask app
CMD ["python", "app.py"]
